
include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: tester_xiao
  - board: seeeduino_xiao_ble
    shield: my_keyboard_dongle
# there is no settingsreset (needed) for the XIAO
