file_format: "1"
id: my_keyboard_dongle
name:my_keyboard_dongle
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [xiao_ble]
features:
  - keys
siblings:
  - totem_left
  - totem_right
  - my_keyboard_dongle

